01_cavity: 01_cavity.cpp
	g++ 01_cavity.cpp -O3
02_cavity_openmp: 02_cavity_openmp.cpp
	g++ 02_cavity_openmp.cpp -fopenmp -O3
03_cavity_simd: 03_cavity_simd.cpp
	g++ 03_cavity_simd.cpp -fopt-info-vec-optimized -march=native -O3
